Better AWS integration (#690)
* Add AWS support in axiom-backup

* Fix delete_snapshot

* Fix "use" option

Remove "-w" option from grep because if the snapshot name is not exactly at the beginning or the end of the line, it won't be able to find it.

diff --git a/interact/axiom-images b/interact/axiom-images
--- a/interact/axiom-images
+++ b/interact/axiom-images
@@ -138,7 +138,7 @@ fi
 if [[ "$use" == "true" ]]; then
 old="$(cat "$AXIOM_PATH/axiom.json" | jq -r '.imageid')"
 jq '.imageid="'$snapshot'"' <"$account_path">"$AXIOM_PATH"/tmp.json ; mv "$AXIOM_PATH"/tmp.json "$account_path"
-get_snapshots | grep -w $snapshot || { echo -e "${Red}Failed to find snapshot with name: "$snapshot"... exiting${Color_Off}" ; exit 1; }
+get_snapshots | grep $snapshot || { echo -e "${Red}Failed to find snapshot with name: "$snapshot"... exiting${Color_Off}" ; exit 1; }
 echo -e "${Green}Successfully updated imageid $old with new imageid in $snapshot in account: $current${Color_Off}"
 echo -e "${Green}Run axiom-init or axiom-fleet to use it!${Color_Off}"
 fi
