improve ssh key detection/creation flow

diff --git a/interact/axiom-configure b/interact/axiom-configure
--- a/interact/axiom-configure
+++ b/interact/axiom-configure
@@ -144,10 +144,10 @@ fi
 if [ ! -z "$pubkey" ]; then
   key_comment=$(<"$pubkey" cut -d' ' -f3)
   echo -e "${Blue}Detected SSH public key at ${pubkey} (${key_comment}), would you like me to install this for your axiom setup? y/n ${Color_Off}"
-        read ans
-        if [ $ans == "y" ]; then
-                cat "$pubkey" >$AXIOM_PATH/configs/authorized_keys || echo -e "${Red}SSH key installation failed${Color_Off}"
-        fi
+  read ans
+  if [ $ans == "y" ]; then
+    cat "$pubkey" >$AXIOM_PATH/configs/authorized_keys || echo -e "${Red}SSH key installation failed${Color_Off}"
+  fi
 fi
 
 if [ "$SHELL" == "/usr/local/bin/zsh" ] || [ "$SHELL" == "/usr/bin/zsh" ] || [ "$SHELL" == "/bin/zsh" ]; then
