Update axiom-scan

diff --git a/interact/axiom-scan b/interact/axiom-scan
--- a/interact/axiom-scan
+++ b/interact/axiom-scan
@@ -148,7 +148,7 @@ delete_logs() {
    cd "$AXIOM_PATH/logs/$uid/" ; ls | grep -v output | xargs rm -r >/dev/null 2>&1
    cd "$start"
   else
-    echo "Error: log folder does not exist."
+    echo "Error: local log folder does not exist."
 fi
 }
 
@@ -693,7 +693,8 @@ fi
 if [[ "$command" =~ "_target_" ]]; then
     echo -e "${BRed}[*]${Red} ENABLING ONESHOT MODE! STARTING $(($total_instances * $threads)) TOTAL THREADS. Using $threads threads per instance with $total_instances instances...${Color_Off}"
     sleep 3
-    $interlace_cmd -c "$ssh_command _target_ 'cd $scan_dir; interlace --silent -threads $threads -tL input -cL command -o output' >> $tmp/logs/_target_ 2>&1"
+    $interlace_cmd -c "$ssh_command _target_ 'cd $scan_dir; interlace --silent -threads $threads -tL input -cL command -o output ; touch _target_' >> $tmp/logs/_target_ 2>&1"
+    $interlace_cmd -c "$ssh_command _target_ '[ -f $scan_dir/_target_ ] && echo _target_ finished || echo _target_ scan still running'"
 
 # Once all the SSH terminals exit, either by finishing its exection or if the session drops, download the results
 # TODO: Dont call axiom-scp just because SSH returns, instead periodically SSH into the instances and determine if the scan has finished and then download
@@ -705,9 +706,12 @@ else
 # TODO: Dont call axiom-scp just because SSH returns, instead periodically SSH into the instances and determine if the scan has finished and then download
 # https://github.com/pry0cc/axiom/issues/398#issuecomment-884558443
     if [[ "$interactive" == "true" ]]; then
-        $interlace_cmd -c "$ssh_command _target_ 'cd $scan_dir; $command'"
+        $interlace_cmd -c "$ssh_command _target_ 'cd $scan_dir; $command; touch _target_'"
+        $interlace_cmd -c "$ssh_command _target_ '[ -f $scan_dir/_target_ ] && echo _target_ finished || echo _target_ scan still running'"
+
     else
-        $interlace_cmd -c "$ssh_command _target_ 'cd $scan_dir; $command' >> $tmp/logs/_target_ 2>&1"
+        $interlace_cmd -c "$ssh_command _target_ 'cd $scan_dir; $command;touch _target_' >> $tmp/logs/_target_ 2>&1"
+        $interlace_cmd -c "$ssh_command _target_ '[ -f $scan_dir/_target_ ] && echo _target_ finished || echo _target_ scan still running'"
     fi
     $interlace_cmd -c "axiom-scp _target_:$scan_dir/output $tmp/output/_target_.$ext --cache -F=$sshconfig >/dev/null 2>&1"
 fi
