Update axiom-configure
fix go install, and amass config

diff --git a/interact/axiom-configure b/interact/axiom-configure
--- a/interact/axiom-configure
+++ b/interact/axiom-configure
@@ -87,7 +87,9 @@ if [ $BASEOS == "Linux" ]; then
         echo "$USER soft nofile 655350" | sudo tee -a /etc/security/limits.conf > /dev/null
         echo "root hard nofile 655350" | sudo tee -a /etc/security/limits.conf > /dev/null
         echo "root soft nofile 655350" | sudo tee -a /etc/security/limits.conf > /dev/null
+        mkdir "${HOME}/.ssh/"
         mkdir "${HOME}/.ssh/sockets"
+        mkdir "${HOME}/.axiom/tmp/"
 
 
     
@@ -125,72 +127,78 @@ if [ $BASEOS == "Linux" ]; then
         echo "$USER soft nofile 655350" | sudo tee -a /etc/security/limits.conf > /dev/null
         echo "root hard nofile 655350" | sudo tee -a /etc/security/limits.conf > /dev/null
         echo "root soft nofile 655350" | sudo tee -a /etc/security/limits.conf > /dev/null
+        mkdir "${HOME}/.ssh/"
         mkdir "${HOME}/.ssh/sockets"
+        mkdir "${HOME}/.axiom/tmp/"
 
 	fi
 fi
 
-#install go
-whereis go
-if [ ! $? -eq 0 ] && [[ -z "$GOPATH" ]]; then
-    echo -e "${Blue}It looks like go is not installed, would you like to install it now${Color_Off}"
-    PS3="Please select an option : "
-    choices=("yes" "no")
-    select choice in "${choices[@]}"; do
-        case $choice in
-        yes)
 
-            echo -e "${Blue}Installing Golang${Color_Off}"
-            wget https://golang.org/dl/go1.14.4.linux-amd64.tar.gz
-            sudo tar -xvf go1.14.4.linux-amd64.tar.gz
-            sudo mv go /usr/local
-            export GOROOT=/usr/local/go
-            export GOPATH=$HOME/go
-            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
-            echo 'export GOROOT=/usr/local/go' >>~/.bash_profile
-            echo 'export GOPATH=$HOME/go' >>~/.bash_profile
-            echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >>~/.bash_profile
-            source ~/.bash_profile
-            sleep 1
-            break
-            ;;
-        no)
-            echo -e "${Red}Please install go and rerun this script"
-            echo -e "Aborting installation...${Color_Off}"
-            exit 1
-            ;;
-        esac
-    done
+#install go
+if ! [ -x "$(command -v go)" ]; then
+       echo -e "${Blue}It looks like go is not installed, would you like to install it now${Color_Off}"
+       PS3="Please select an option : "
+       choices=("yes" "no")
+       select choice in "${choices[@]}"; do
+       case $choice in
+       yes)
+
+       echo -e "${Blue}Installing Golang${Color_Off}"
+       wget https://golang.org/dl/go1.14.4.linux-amd64.tar.gz
+       sudo tar -C /usr/local -xzf go1.14.4.linux-amd64.tar.gz 
+       mkdir "${HOME}/go"
+       export GOROOT=/usr/local/go/
+       export GOPATH=$HOME/go
+       export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
+       echo 'export GOROOT=/usr/local/go/' >>~/.bash_profile
+       echo 'export GOPATH=$HOME/go' >>~/.bash_profile
+       echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >>~/.bash_profile
+       source ~/.bash_profile
+       sleep 1
+       break
+       ;;
+       no)
+       echo -e "${Red}Please install go and rerun this script"
+       echo -e "Aborting installation...${Color_Off}"
+       exit 1
+       ;;
+   esac 
+   done
 fi
 
 if [ $BASEOS == "Mac" ]; then
-  whereis brew
+         whereis brew
   if [ ! $? -eq 0 ] || [[ ! -z ${AXIOM_FORCEBREW+x} ]]; then
-    echo -e "${Blue}Installing brew...${Color_Off}"
-    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+         echo -e "${Blue}Installing brew...${Color_Off}"
+         /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
   else
-    echo -e "${Blue}Checking for brew... already installed, skipping installation.${Color_Off}"
-    echo -e "${Blue}    Note: You can force brew installation by running${Color_Off}"
-    echo -e '    $ AXIOM_FORCEBREW=yes $HOME/.axiom/interact/axiom-configure'
+         echo -e "${Blue}Checking for brew... already installed, skipping installation.${Color_Off}"
+         echo -e "${Blue}    Note: You can force brew installation by running${Color_Off}"
+         echo -e '    $ AXIOM_FORCEBREW=yes $HOME/.axiom/interact/axiom-configure'
   fi
-    echo -e "${Blue}Installing doctl...${Color_Off}"
-    brew install doctl
-  echo -e "${Blue}Installing go...${Color_Off}"
-    brew install golang
-  echo -e "${Blue}Installing ibmcloud cli...${Color_Off}"
-  curl -fsSL https://clis.cloud.ibm.com/install/osx | sh
-    echo -e "${Blue}Installing jq...${Color_Off}"
-    brew install jq
-  echo -e "${Blue}Installing coreutils...${Color_Off}"
-  brew install coreutils
-    echo -e "${Blue}Installing packer...${Color_Off}"
-    mkdir -p $(go env GOPATH)/src/github.com/hashicorp && cd $_
-    sudo rm -r packer/ ; git clone https://github.com/hashicorp/packer.git
-    cd packer
-    make dev
-  export PATH=$PATH:$(go env GOPATH)/bin
-  source ~/.bash_profile
-  mkdir "${HOME}/.ssh/sockets"
+         echo -e "${Blue}Installing doctl...${Color_Off}"
+         brew install doctl
+         echo -e "${Blue}Installing go...${Color_Off}"
+         brew install golang
+         echo -e "${Blue}Installing ibmcloud cli...${Color_Off}"
+         curl -fsSL https://clis.cloud.ibm.com/install/osx | sh
+         echo -e "${Blue}Installing jq...${Color_Off}"
+         brew install jq
+         echo -e "${Blue}Installing coreutils...${Color_Off}"
+         brew install coreutils
+         echo -e "${Blue}Installing packer...${Color_Off}"
+         mkdir -p $(go env GOPATH)/src/github.com/hashicorp && cd $_
+         sudo rm -r packer/ ; git clone https://github.com/hashicorp/packer.git
+         echo -e "${Blue}Installing Python3...${Color_Off}"
+         brew install python3
+         cd packer
+         make dev
+         export PATH=$PATH:$(go env GOPATH)/bin
+         source ~/.bash_profile
+         mkdir "${HOME}/.ssh/"
+         mkdir "${HOME}/.ssh/sockets"
+         mkdir "${HOME}/.axiom/tmp/"
 fi
 
 if [ ! -d $AXIOM_PATH ]; then
