Update axiom-images

diff --git a/interact/axiom-images b/interact/axiom-images
--- a/interact/axiom-images
+++ b/interact/axiom-images
@@ -20,8 +20,8 @@ current=$(ls -lh ~/.axiom/axiom.json | awk '{ print $11 }' | tr '/' '\n' | grep 
 
 function usage() {
   cat << EOF
-  Usage: axiom-images ls
-  Examples:
+  Examples: axiom-images ls && axiom-images rm axiom-barebones-1634682130 && axiom-images use axiom-default-1634682131
+  Usage:
   ls                                 List snapshots created
   use               Use snapshot for axiom-init/axiom-fleet
   rm                           Remove snapshot from account
@@ -36,7 +36,6 @@ list=false
 help=true
 rm=false
 use=false
-
 # Parse command line arguments 
 #
 i=0
@@ -102,17 +101,22 @@ fi
 # List Snapshots
 #
 if [[ "$list" == "true" ]]; then
-echo -e "Listing Available Snapshots in Account: $current"
+echo -e "${Green}Listing Available Snapshots in Account: $current${Color_Off}"
 get_snapshots
+exit 1
 fi
+
+# If snapshot name not supplied, exit
+#
+if [ -z ${snapshot:+x} ]; then echo -e "${Red}Snapshot name not supplied. To list all snapshots run axiom-images ls${Color_Off}" && exit 1; fi
 
 
 # Delete Snapshot by its name
 #
 if [[ "$rm" == "true" ]]; then
-echo -e "Deleting Snapshot by name: $(echo $snapshot)"
-delete_snapshot $snapshot || echo "Failed to delete snapshot"
-echo -e "Successfully deleted snapshot!"
+echo -e "${Green}Deleting Snapshot by name: $(echo $snapshot)${Color_Off}"
+delete_snapshot $snapshot || { echo -e "${Red}Failed to find snapshot with name: "$snapshot"... exiting${Color_Off}" ; exit 1; }
+echo -e "${Green}Successfully deleted snapshot!${Color_Off}"
 fi
 
 # Use Snapshot by name. Run axiom-init or axiom-fleet to use after updating
@@ -120,7 +124,7 @@ fi
 if [[ "$use" == "true" ]]; then
 old="$(cat "$AXIOM_PATH/axiom.json" | jq -r '.imageid')"
 jq '.imageid="'$snapshot'"' <"$account_path">"$AXIOM_PATH"/tmp.json ; mv "$AXIOM_PATH"/tmp.json "$account_path"
-get_snapshots | grep -w $snapshot || { echo 'Failed to find snapshot with name "'"$snapshot"'"... exiting' ; exit 1; } 
-echo -e "Successfully updated imageid $old with new imageid in $snapshot in account: $current"
-echo -e "Run axiom-init or axiom-fleet to use it!"
+get_snapshots | grep -w $snapshot || { echo -e "${Red}Failed to find snapshot with name: "$snapshot"... exiting${Color_Off}" ; exit 1; }
+echo -e "${Green}Successfully updated imageid $old with new imageid in $snapshot in account: $current${Color_Off}"
+echo -e "${Green}Run axiom-init or axiom-fleet to use it!${Color_Off}"
 fi
