docker support for controller (#425)
* Update axiom-configure

diff --git a/interact/axiom-configure b/interact/axiom-configure
--- a/interact/axiom-configure
+++ b/interact/axiom-configure
@@ -50,19 +50,23 @@ case $BASEOS in
 *) ;;
 esac
 
-if [ $BASEOS == "Linux" ]; then
+if [[ $BASEOS == "Linux" ]]; then
     if $(uname -a | grep -qi "Microsoft"); then
         OS="UbuntuWSL"
     else
-        if ! command -v lsb_release &> /dev/null; then
-            echo "lsb_release could not be found, unable to determine your distribution"
-            echo "If you are using Arch, please get lsb_release from AUR"
-            exit 1
-        fi
         OS=$(lsb_release -i | awk '{ print $3 }')
+        if ! command -v lsb_release &> /dev/null; then
+            echo "ERROR: This install might not work"
+            echo "lsb_release could not be found, unable to determine your distribution"
+            OS="unknown-Linux"
+            BASEOS="Linux"
+            shell="bash"
+        fi
     fi
 
-    if [ $OS == "Arch" ] || [ $OS == "ManjaroLinux" ]; then
+
+
+    if [[ $OS == "Arch" ]] || [[ $OS == "ManjaroLinux" ]]; then
         echo -e "${Blue}Congrats, you run arch..."
         echo -e "${Blue}Installing other repo deps...${Color_Off}"
         # Stated dependencies in the Github-wiki
@@ -79,11 +83,14 @@ if [ $BASEOS == "Linux" ]; then
         # Would probably suffice with running 'go'...
         GOPATH_TEMP=$(eval which go)
         eval GOPATH_TEMP get -u github.com/sensepost/gowitness@2.3.6
-    elif [ $OS == "Ubuntu" ] || [ $OS == "Debian" ] || [ $OS == "Linuxmint" ] || [ $OS == "Parrot" ] || [ $OS == "Kali" ]; then
+    elif [[ $OS == "Ubuntu" ]] || [[ $OS == "Debian" ]] || [[ $OS == "Linuxmint" ]] || [[ $OS == "Parrot" ]] || [[ $OS == "Kali" ]] || [[ $OS == "unknown-Linux" ]]; then
+       if ! command -v sudo &> /dev/null; then
+        apt update && apt-get install sudo -y -qq
+       fi
         echo -e "${Blue}Installing other repo deps...${Color_Off}"
-        sudo apt-get update && sudo apt-get install git ruby python3-pip curl net-tools unzip xsltproc bc rsync -y 
+        DEBIAN_FRONTEND=noninteractive sudo apt-get update && sudo apt-get install git ruby python3-pip curl net-tools unzip xsltproc bc rsync sudo wget nano bsdmainutils -y 
         echo -e "${Blue}Installing jq...${Color_Off}"
-        sudo wget -O /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && sudo chmod +x /usr/bin/jq 
+        sudo wget -q -O /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && sudo chmod +x /usr/bin/jq 
         echo -e "${Blue}Installing packer...${Color_Off}"
         wget -O /tmp/packer.zip https://releases.hashicorp.com/packer/1.5.6/packer_1.5.6_linux_amd64.zip && cd /tmp/ && unzip packer.zip && sudo mv packer /usr/bin/ && rm /tmp/packer.zip 
         echo -e "${Blue}Installing Interlace...${Color_Off}"
@@ -92,7 +99,7 @@ if [ $BASEOS == "Linux" ]; then
         echo -e "${Blue}Installing gowitness...${Color_Off}"
         sudo wget -O /usr/bin/gowitness https://github.com/sensepost/gowitness/releases/download/2.3.6/gowitness-2.3.6-linux-amd64 && sudo chmod +x /usr/bin/gowitness 
 
-	elif [ $OS == "Fedora" ]; then
+	elif [[ $OS == "Fedora" ]]; then
       	echo -e "${Blue}Installing other repo deps...${Color_Off}"
 		    sudo dnf update && sudo dnf -y install mmv bc fzf git rubypick python3-pip curl net-tools unzip util-linux
 		    echo -e "${Blue}Installing jq...${Color_Off}"
@@ -104,11 +111,11 @@ if [ $BASEOS == "Linux" ]; then
         echo -e "${Blue}Installing gowitness...${Color_Off}"
         sudo wget -O /usr/bin/gowitness https://github.com/sensepost/gowitness/releases/download/2.3.6/gowitness-2.3.6-linux-amd64 && sudo chmod +x /usr/bin/gowitness 
 
-  elif [ $OS == "UbuntuWSL" ]; then
+  elif [[ $OS == "UbuntuWSL" ]]; then
         echo -e "${Blue}Installing other repo deps...${Color_Off}"
-        sudo apt-get update && sudo apt-get install git ruby python3-pip curl net-tools unzip xsltproc bc rsync -y 
+        DEBIAN_FRONTEND=noninteractive sudo apt-get update && sudo apt-get install git ruby python3-pip curl net-tools unzip xsltproc bc rsync sudo nano wget bsdmainutils -y 
         echo -e "${Blue}Installing jq...${Color_Off}"
-        sudo wget -O /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && sudo chmod +x /usr/bin/jq
+        sudo wget -q -O /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && sudo chmod +x /usr/bin/jq
         echo -e "${Blue}Installing packer...${Color_Off}"
         wget -O /tmp/packer.zip https://releases.hashicorp.com/packer/1.5.6/packer_1.5.6_linux_amd64.zip && cd /tmp/ && unzip packer.zip && sudo mv packer /usr/bin/ && rm /tmp/packer.zip
         echo -e "${Blue}Installing Interlace...${Color_Off}"
@@ -119,8 +126,7 @@ if [ $BASEOS == "Linux" ]; then
 	fi
 fi
 
-
-if [ $BASEOS == "Mac" ]; then
+if [[ $BASEOS == "Mac" ]]; then
          echo -e "${Blue}Installing Brew...${Color_Off}"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo -e 'Setting permissions'
@@ -155,7 +161,25 @@ if [ $BASEOS == "Mac" ]; then
          SHELL=$(which zsh)
 fi
 
-if [ $BASEOS == "Linux" ]; then
+if [[ $BASEOS == "Linux" ]]; then
+if [[ $shell == "bash" ]]; then
+    echo -e "${Blue}Installing Golang${Color_Off}"
+    wget https://golang.org/dl/go1.16.3.linux-amd64.tar.gz
+    sudo tar -C /usr/local -xzf go1.16.3.linux-amd64.tar.gz 
+    rm go1.16.3.linux-amd64.tar.gz
+    mkdir -p "${HOME}/go"
+    export GOPATH=$HOME/go
+    export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH    
+    echo "export GOPATH=\$HOME/go" >> ${HOME}/.bashrc
+    echo "export PATH=\$GOPATH/bin:/usr/local/go/bin:$PATH" >> ${HOME}/.bashrc
+    source ${HOME}/.bashrc
+    SHELL=$(which bash)
+    echo -e "${Green}You're running Bash! Installing Axiom to \$PATH...${Color_Off}"
+    echo "export PATH=\"\$PATH:\$HOME/.axiom/interact\"" >>~/.bashrc
+    echo "[[ -f ~/.bashrc ]] && . ~/.bashrc" >> ${HOME}/.bash_profile
+    source ~/.bashrc 
+else
+
 # Pick your shell
 echo -e "${Blue}Would you like to use Bash or Oh My Zsh? ${Color_Off}"
  PS3="Please select an option : "
@@ -202,6 +226,7 @@ echo -e "${Blue}Would you like to use Bash or Oh My Zsh? ${Color_Off}"
    ;;
 esac
 done
+fi
 fi
 
 #install gee
